config/routes.rb
Rails.application.routes.draw do
  root 'episodes#index'
  resources :episodes
  resources :stories
  resources :illustrations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_many :stories
end

app/models/illustration.rb
class Illustration < ApplicationRecord
  belongs_to :story
  mount_uploader :image, ImageUploader
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :episode
  has_many :illustrations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @episodes = Episode.all
  end

  def new
    @episode = Episode.new
  end

  def create
  	episode = Episode.create(episode_params)
  	if episode.valid?
  		redirect_to episodes_path
  	else
  		# it would be good to render an error here as well
  		flash[:error] = episode.errors
  		render :new
  	end
  end

  private

  def episode_params
  	params.require(:episode).permit(:name, :description, :date)
  end

end

app/controllers/illustrations_controller.rb
class IllustrationsController < ApplicationController

  def index
    @illustrations = Illustration.all
  end

  def new
    @illustration = Illustration.new
  end

  def create
    @illustration = Illustration.new
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = stories.create
    redirect_to new_story_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/index.html.erb
<% @episodes.each do |episode| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title"><%= episode.name %></h4>
        <p class="card-text"><%= episode.description %></p>
      </div>
      <div class="card-footer">
        <small class="text-muted"><%= episode.date %></small>
      </div>
    </div>
  </div>
  <hr />
<% end %>

<div class="card-deck">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Name</h4> <!-- Episode title goes here (:name) -->
      <p class="card-text">Description</p> <!-- Episode description goes here (:description) -->
    </div>
    <div class="card-footer">
      <small class="text-muted">Date</small> <!-- Episode date goes here -->
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

<div class="card-deck">
  <div class="card">
      <div class="card-body">
        <h4 class="card-title">Card title</h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
      </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>

app/views/episodes/new.html.erb
<div class="episode-box col-10 offset-1">
<h1>Enter a New Episode</h1>
<%= simple_form_for @episode do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :date %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/illustrations/index.html.erb
<h1>You may want a list of your illustrations here</h1>

app/views/illustrations/new.html.erb
<div class="form-box col-10 offset-1">
<h1>New Illustration</h1>
<%= simple_form_for @illustration do |f| %>
  <%= f.input :caption %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>


</div>

app/views/illustrations/show.html.erb
<h1>Hello world</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flight of The Fallingstar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light justify-content-center">
      <%= link_to 'Flight of the Fallingstar', root_path, class: "navbar-brand" %>
    </nav>

    <ul class="nav justify-content-center">
      <li class="nav-item">
        <%= link_to 'Stories', stories_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Illustrations', illustrations_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Reviews', '#', class: 'nav-link' %>
      </li>
    </ul>
    <br class="clear" />
    <%= yield %>
  </body>
</html>

app/views/stories/index.html.erb
<h1>Hello world</h1>

app/views/stories/new.html.erb
<div class="episode-box col-10 offset-1">
<h1>New Story</h1>
<%= simple_form_for @story do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :author %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>
</div>